import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';
import compress from 'astro-compress';

// Blog post slugs from production sitemap - redirect old URLs to /berita/{slug}
const blogSlugs = [
  'bikin-jaket-kelas-murah-dan-bisa-desain-sendiri-di-surabaya',
  'custom-jaket-varsity-bitung',
  'custom-jaket-varsity-mamuju',
  'custom-jaket-varsity-yogyakarta',
  'custom-jaket-varsity-bogor',
  'custom-jaket-varsity-tangerang',
  'custom-jaket-varsity-bekasi',
  'custom-jaket-varsity-bandung',
  'custom-jaket-varsity-jakarta',
  'custom-jaket-varsity-depok',
  'custom-jaket-varsity-semarang',
  'custom-jaket-varsity-malang',
  'custom-jaket-varsity-surabaya',
  'custom-jaket-varsity-sidoarjo',
  'custom-jaket-varsity-palopo',
  'custom-jaket-varsity-tomohon',
  'custom-jaket-varsity-pare-pare',
  'custom-jaket-varsity-gorontalo',
  'custom-jaket-varsity-palu',
  'custom-jaket-varsity-manado',
  'custom-jaket-varsity-makassar',
  'custom-jaket-varsity-ketapang',
  'custom-jaket-varsity-tenggarong',
  'custom-jaket-varsity-singkawang',
  'custom-jaket-varsity-banjarbaru',
  'custom-jaket-varsity-bontang',
  'custom-jaket-varsity-tarakan',
  'custom-jaket-varsity-palangkaraya',
  'custom-jaket-varsity-pontianak',
  'custom-jaket-varsity-balikpapan',
  'custom-jaket-varsity-samarinda',
  'custom-jaket-varsity-banjarmasin',
  'custom-jaket-varsity-dumai',
  'custom-jaket-varsity-aceh',
  'custom-jaket-varsity-pangkal-pinang',
  'custom-jaket-varsity-bengkulu',
  'custom-jaket-varsity-jambi',
  'custom-jaket-varsity-padang',
  'custom-jaket-varsity-batam',
  'custom-jaket-varsity-pekanbaru',
  'custom-jaket-varsity-bandar-lampung',
  'custom-jaket-varsity-palembang',
  'custom-jaket-varsity-medan',
  'custom-jaket-varsity-kendari',
  'custom-jaket-varsity-bau-bau',
  'memilih-jaket-kelas-jaket-angkatan-dan-jaket-himpunan',
  'vendor-jaket-kelas-jakarta',
  'vendor-jaket-kelas-bekasi',
  'vendor-jaket-kelas-tangerang',
  'vendor-jaket-kelas-depok',
  'vendor-jaket-kelas-semarang',
  'vendor-jaket-kelas-bogor',
  'vendor-jaket-kelas-malang',
  'vendor-jaket-kelas-yogyakarta',
  'vendor-jaket-kelas-sidoarjo',
  'vendor-jaket-kelas-surabaya',
  'vendor-jaket-kelas-bandung',
  'vendor-jaket-kelas-makassar',
  'vendor-jaket-kelas-manado',
  'vendor-jaket-kelas-palu',
  'vendor-jaket-kelas-kendari',
  'vendor-jaket-kelas-gorontalo',
  'vendor-jaket-kelas-bitung',
  'vendor-jaket-kelas-pare-pare',
  'vendor-jaket-kelas-bau-bau',
  'vendor-jaket-kelas-tomohon',
  'vendor-jaket-kelas-palopo',
  'vendor-jaket-kelas-mamuju',
  'vendor-jaket-kelas-ketapang',
  'vendor-jaket-kelas-tenggarong',
  'vendor-jaket-kelas-singkawang',
  'vendor-jaket-kelas-banjarbaru',
  'vendor-jaket-kelas-bontang',
  'vendor-jaket-kelas-tarakan',
  'vendor-jaket-kelas-palangkaraya',
  'vendor-jaket-kelas-pontianak',
  'vendor-jaket-kelas-balikpapan',
  'vendor-jaket-kelas-samarinda',
  'vendor-jaket-kelas-banjarmasin',
  'vendor-jaket-kelas-dumai',
  'vendor-jaket-kelas-aceh',
  'vendor-jaket-kelas-pangkal-pinang',
  'vendor-jaket-kelas-bengkulu',
  'vendor-jaket-kelas-jambi',
  'vendor-jaket-kelas-padang',
  'vendor-jaket-kelas-batam',
  'vendor-jaket-kelas-pekanbaru',
  'vendor-jaket-kelas-bandar-lampung',
  'vendor-jaket-kelas-palembang',
  'vendor-jaket-kelas-medan',
  'tren-fashion-anak-muda',
  'koleksi-spesial-seragam-sekolah',
  'pakaian-casual-untuk-hangout',
  'kustomisasi-pakaian-ekspresikan-diri-anda',
  'proses-produksi-jaket-angkatan-berkualitas-di-level-garment',
  'tren-jaket-angkatan-untuk-siswa-sd-smp-dan-sma',
  'tips-memilih-jaket-angkatan-yang-keren-dan-nyaman-untuk-siswa-smp-dan-sma',
  'kenapa-jaket-varsity-menjadi-pilihan-favorit-untuk-jaket-angkatan',
  'langkah-langkah-memilih-kain-untuk-jaket-kelas-yang-tahan-lama-dan-nyaman',
  'panduan-memilih-jersey-berkualitas-untuk-tim-anda',
  'kenapa-pilih-level-garment-untuk-produksi-jersey-anda',
  'cara-memilih-bahan-jaket-varsity',
  'perbedaan-jaket-varsity-dan-jaket-bomber',
  'tren-fashion-anak-muda-bagaimana-brand-garment-bisa-menyesuaikan-diri',
  'streetwear-vs-casual-wear-mana-yang-lebih-diminati-anak-muda',
  'rahasia-sukses-brand-garment-yang-disukai-anak-muda',
  'workshirt-lengan-panjang',
  'workshirt-denim',
  'workshirt-pria',
  'kenapa-seragam-pdl-dan-pdh-penting-untuk-organisasi-pelajar',
  'inspirasi-desain-jersey-baseball-untuk-komunitas-dan-kegiatan-sekolah',
  'panduan-memilih-jaket-varsity-untuk-kelas-dan-angkatan',
  'konveksi-surabaya',
  'konveksi-jaket-varsity-pelajar-terbaik-di-surabaya',
  'workshirt-custom-untuk-osis-ekstrakurikuler-dan-komunitas-sekolah',
  'tempat-bikin-seragam-komunitas-pelajar-custom-satuan',
  'konveksi-jersey-pelajar-cocok-untuk-futsal-basket-dan-e-sport',
  'kenapa-pelajar-dan-mahasiswa-pilih-level-garment-untuk-outfit-komunitasnya',
  'inspirasi-desain-jaket-varsity-untuk-siswa-sma-dan-mahasiswa',
  '10-ide-jersey-kelas-atau-angkatan-yang-kekinian-dan-keren',
  'desain-workshirt-sekolah-yang-stylish-dan-serbaguna',
  'gaya-pelajar-aktif-inspirasi-mix-match-jaket-varsity-dari-level-garment',
  'perbedaan-jaket-varsity-bahan-fleece-vs-drill',
  'cara-ukur-jaket-dan-workshirt-agar-pas-untuk-semua-ukuran-badan',
  'bikin-outfit-komunitas-yang-kompak-tips-warna-dan-logo',
  'keunggulan-jersey',
  'jersey-sebagai-fashion-casual',
  'konveksi-jaket-kelas-dan-angkatan-surabaya',
  'cara-memilih-jersey',
];

// Generate redirects object: /slug -> /berita/slug
const blogRedirects = {};
blogSlugs.forEach(slug => {
  blogRedirects[`/${slug}`] = `/berita/${slug}`;
});

export default defineConfig({
  site: 'https://levelgarment.com',
  integrations: [
    tailwind({
      applyBaseStyles: false,
    }),
    sitemap({
      xslURL: '/sitemap.xsl',
    }),
    compress({
      CSS: true,
      HTML: true,
      Image: false, // CLI 6 handles this
      JavaScript: true,
      SVG: true,
    })
  ],
  output: 'static',
  redirects: blogRedirects,
  build: {
    assets: '_assets'
  },
  vite: {
    build: {
      cssCodeSplit: true,
      rollupOptions: {
        output: {
          assetFileNames: '_assets/[name].[hash][extname]'
        }
      }
    }
  }
});
